version: "3"

services:
  rabbimq:
    build: .
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=ismewen
      - RABBITMQ_DEFAULT_PASS=ismewen

  mysql_db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ismewen

  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: ismewen
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"

    restart: unless-stopped

volumes:
  mysql_data:
  postgres:





