version: "3"

services:

  elasticsearch:
    image: elasticsearch:6.6.1
    ports:
      - "9200:9200"
    restart: always
    networks:
      - es

  kinbana:
    image: kibana:6.6.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - es
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  apm:
    image: elastic/apm-server:6.6.1
    ports:
      - "8200:8200"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - es
    depends_on:
      - elasticsearch
      - kinbana

  logstash:
    image: elastic/logstash:6.6.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - es
    depends_on:
      - elasticsearch
      - kinbana
    volumes:
      - ./log:/log
      - ./elk/settings/logstash.conf:/usr/share/logstash/config/logstash.conf


  filebeat:
    image:  docker.elastic.co/beats/filebeat:6.6.1
    restart: always
    networks:
      - es

networks:
  es:


volumes:
  mysql_data:
